### ISSUE TITLE
segfault when zmq source set and reload

### ISSUE THREAD

**Issue by lmesz** [lmesz/syslog-ng-incubator#2]

**Comment by lmesz** [comment]
The stacktrace is the following:
#0  persist_state_map_entry (self=0x0, handle=0) at lib/persist-state.c:705
No locals.
#1  0x00007f256c279fef in _buffered_server_bookmark_save (bookmark=0x7043a0) at lib/logproto/logproto-buffered-server.c:739
        bookmark_data = 0x7043b8
        state = <optimized out>
#2  0x00007f256c2714cf in late_ack_tracker_manage_msg_ack (s=0x704300, msg=0x7f2558005e00, ack_type=AT_PROCESSED) at lib/late_ack_tracker.c:139
        bookmark = <optimized out>
        self = 0x704300
        ack_rec = <optimized out>
        last_in_range = <optimized out>
        ack_range_length = <optimized out>
#3  0x00007f256c25cf5d in log_msg_refcache_stop () at lib/logmsg.c:1552
        ack_type_cummulated = AT_PROCESSED
        old_value = 7357328
        current_cached_acks = <optimized out>
        current_cached_abort = <optimized out>
        __func__ = "log_msg_refcache_stop"
#4  0x00007f256c25ee90 in log_reader_handle_line (aux=0x7f25683c55d0, length=<optimized out>, line=<optimized out>, self=0x704040) at lib/logreader.c:321
        m = 0x7f2558005e00
        path_options = {ack_needed = -1, flow_control_requested = 0, matched = 0x0}
#5  log_reader_fetch_log (self=self@entry=0x704040) at lib/logreader.c:381
        msg = 0x7f2558003000 "Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Almafa!Alma"...
        msg_len = 672
        msg_count = 1
        may_read = 1
        aux = {peer_addr = 0x0, data = '\000' <repeats 400 times>..., end_ptr = 0}
        **func** = "log_reader_fetch_log"
#6  0x00007f256c25f069 in log_reader_work_perform (s=0x704040) at lib/logreader.c:86
        self = 0x704040
#7  0x00007f256c265eed in _work (self=<optimized out>) at lib/mainloop-io-worker.c:52
No locals.
#8  0x00007f256c289da7 in iv_work_thread_do_work (_thr=0x71d0c0) at iv_work.c:118
        work = 0x7041d0
        thr = 0x71d0c0
        pool = 0x6f88c0
        last_seq = 2
#9  0x00007f256c289113 in iv_run_tasks (st=st@entry=0x7f2558002630) at iv_task.c:48
        t = <optimized out>
        tasks = {next = 0x7f25683c5a90, prev = 0x7f25683c5a90}
#10 0x00007f256c28b2ec in iv_main () at iv_main_posix.c:106
        to = {tv_sec = 139798366919456, tv_nsec = 139798701653670}
#11 0x00007f256c289bf4 in iv_work_thread (_thr=0x71d0c0) at iv_work.c:200
        thr = 0x71d0c0
        pool = 0x6f88c0
#12 0x00007f256c28b9d6 in iv_thread_handler (_thr=0x71dfb0) at iv_thread_posix.c:142
        __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {7462832, -3590050144532159186, 0, 0, 139798639315392, 139798639314688, 3487831283465332014, 
                3487840254489011502}, __mask_was_saved = 0}}, __pad = {0x7f25683c5bb0, 0x0, 0x0, 0x6ef568}}
        __cancel_arg = 0x71dfb0
        __not_first_call = <optimized out>
        thr = 0x71dfb0
#13 0x00007f256bd09182 in start_thread (arg=0x7f25683c8700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x7f25683c8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139798639314688, -3590050144532159186, 0, 0, 139798639315392, 139798639314688, 3487831283442263342, 
                3487830976582133038}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#14 0x00007f256ba3647d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.
